# Copyright 2024 The android_world Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Registers the task classes."""

import types
from typing import Any

from android_world.task_evals import task_eval
from android_world.task_evals.composite import markor_sms
from android_world.task_evals.composite import system as system_composite
from android_world.task_evals.information_retrieval import information_retrieval
from android_world.task_evals.information_retrieval import information_retrieval_registry
from android_world.task_evals.miniwob import miniwob_registry
from android_world.task_evals.single import audio_recorder
from android_world.task_evals.single import browser
from android_world.task_evals.single import camera
from android_world.task_evals.single import clock
from android_world.task_evals.single import contacts
from android_world.task_evals.single import expense
from android_world.task_evals.single import files
from android_world.task_evals.single import markor
from android_world.task_evals.single import osmand
from android_world.task_evals.single import recipe
from android_world.task_evals.single import retro_music
from android_world.task_evals.single import simple_draw_pro
from android_world.task_evals.single import simple_gallery_pro
from android_world.task_evals.single import sms
from android_world.task_evals.single import system
from android_world.task_evals.single import vlc
from android_world.task_evals.single import phone
from android_world.task_evals.single.calendar import calendar
from android_world.task_evals.single import markorandcalender
from android_world.task_evals.composite import audio_recorder_camera
from android_world.task_evals.composite import audio_recorder_clock
from android_world.task_evals.composite import camera_clock
from android_world.task_evals.composite import system_camera
from android_world.task_evals.composite import system_clock
from android_world.task_evals.composite import calendar_clock
from android_world.task_evals.composite import Markor_single_draw_pro
from android_world.task_evals.composite import Markor_Camera
from android_world.task_evals.composite import markor_audio_recorder
from android_world.task_evals.composite import markor_clock
from android_world.task_evals.composite import markor_clock_camera
from android_world.task_evals.composite import Markor_camera_audio
from android_world.task_evals.composite import recipe_gallery
def get_information_retrieval_task_path() -> None:
  return None


def get_families() -> list[str]:
  return [
      TaskRegistry.ANDROID_WORLD_FAMILY,
      TaskRegistry.ANDROID_FAMILY,
      TaskRegistry.MINIWOB_FAMILY,
      TaskRegistry.MINIWOB_FAMILY_SUBSET,
      TaskRegistry.INFORMATION_RETRIEVAL_FAMILY,
  ]


class TaskRegistry:
  """Registry of tasks."""

  # The AndroidWorld family.
  ANDROID_WORLD_FAMILY = 'android_world'  # Entire suite.
  ANDROID_FAMILY = 'android'  # Subset.
  INFORMATION_RETRIEVAL_FAMILY = 'information_retrieval'  # Subset.

  # The MiniWoB family.
  MINIWOB_FAMILY = 'miniwob'
  MINIWOB_FAMILY_SUBSET = 'miniwob_subset'

  # Task registries; they contain a mapping from each task name to its class,
  # to construct instances of a task.
  ANDROID_TASK_REGISTRY = {}
  INFORMATION_RETRIEVAL_TASK_REGISTRY = (
      information_retrieval_registry.InformationRetrievalRegistry[
          information_retrieval.InformationRetrieval
      ](filename=get_information_retrieval_task_path()).registry
  )

  MINIWOB_TASK_REGISTRY = miniwob_registry.TASK_REGISTRY

  def get_registry(self, family: str) -> Any:
    """Gets the task registry for the given family.

    Args:
      family: The family.

    Returns:
      Task registry.

    Raises:
      ValueError: If provided family doesn't exist.
    """
    if family == self.ANDROID_WORLD_FAMILY:
      return {
          **self.ANDROID_TASK_REGISTRY,
          **self.INFORMATION_RETRIEVAL_TASK_REGISTRY,
      }
    elif family == self.ANDROID_FAMILY:
      return self.ANDROID_TASK_REGISTRY
    elif family == self.MINIWOB_FAMILY:
      return self.MINIWOB_TASK_REGISTRY
    elif family == self.MINIWOB_FAMILY_SUBSET:
      return miniwob_registry.TASK_REGISTRY_SUBSET
    elif family == self.INFORMATION_RETRIEVAL_FAMILY:
      return self.INFORMATION_RETRIEVAL_TASK_REGISTRY
    else:
      raise ValueError(f'Unsupported family: {family}')

  _TASKS = (
      # keep-sorted start
      audio_recorder.AudioRecorderRecordAudio,
      audio_recorder.AudioRecorderRecordAudioWithSettings,
      audio_recorder.AudioRecorderRecordAudioWithFileName,
      audio_recorder.AudioRecorderRecordAudioWithSettingsAndFileName,
      audio_recorder.AudioRecoderOpen,
      browser.BrowserDraw,
      browser.BrowserMaze,
      browser.BrowserMultiply,
      browser.BrowserOpen,
      calendar.SimpleCalendarAddOneEvent,
      calendar.SimpleCalendarAddOneEventInTwoWeeks,
      calendar.SimpleCalendarAddOneEventInOneMonth,
      calendar.SimpleCalendarAddOneEventRelativeDay,
      calendar.SimpleCalendarAddOneEventRelativeDay2,
      calendar.SimpleCalendarAddOneEventTomorrow,
      calendar.SimpleCalendarAddOneEventThedayafterTomorrow,
      calendar.SimpleCalendarAddOneEventInOneWeek,
      calendar.SimpleCalendarAddOneEventInTwoMonth,
      calendar.SimpleCalendarAddRepeatingEvent,
      calendar.SimpleCalendarDeleteEvents,
      calendar.SimpleCalendarDeleteEventsOnRelativeDay,
      calendar.SimpleCalendarDeleteEvents2,
      calendar.SimpleCalendarDeleteEvents3,
      calendar.SimpleCalendarDeleteEvents4,
      calendar.SimpleCalendarDeleteEvents5,
      calendar.SimpleCalendarDeleteEvents6,
      calendar.SimpleCalendarDeleteEvents7,
      calendar.SimpleCalendarDeleteEvents8,
      calendar.SimpleCalendarDeleteEvents9,
      calendar.SimpleCalendarDeleteEvents10,
      calendar.SimpleCalendarDeleteOneEvent,
      calendar.SimpleCalendarOpen,
      camera.CameraTakePhoto,
      camera.CameraTakePhotos,
      camera.CameraTakeVideo,
      camera.CameraTakeVideos,
      camera.CameraTakePhotoAndVideo,
      camera.CameraTakePhotosAndVideos,
      camera.CameraOpen,
      clock.ClockStopWatchPausedVerify,
      clock.ClockStopWatchRunning,
      clock.ClockTimerEntry,
      clock.ClockTimerEntryAndExit,
      clock.ClockStopWatchRunningAndPaused,
      clock.ClockOpen,
      clock.ClockWatchRunningAndReset,
      clock.ClockWatchExit,
      clock.ClockWatchRunningAndResetAndExit,
      contacts.ContactsAddContact,
      contacts.ContactsNewContactDraft,
      contacts.ContactsOpen,
      contacts.ContactsAddAndChangeContact,
      expense.ExpenseAddMultiple,
      expense.ExpenseAddMultipleFromGallery,
      expense.ExpenseAddMultipleFromGallery2,
      expense.ExpenseAddMultipleFromMarkor,
      expense.ExpenseAddMultipleFromMarkor2,
      expense.ExpenseAddMultipleFromMarkor3,
      expense.ExpenseAddMultipleFromMarkor4,
      expense.ExpenseAddMultipleFromMarkor5,
      expense.ExpenseAddMultipleFromMarkor6,
      expense.ExpenseAddMultipleFromMarkor7,
      expense.ExpenseAddMultipleFromMarkor8,
      expense.ExpenseAddMultipleFromMarkor9,
      expense.ExpenseAddMultipleFromMarkor10,
      expense.ExpenseAddSingle,
      expense.ExpenseAddSingleFromMarkor,
      expense.ExpenseAddSingleFromMarkor2,
      expense.ExpenseAddSingleFromMarkor3,
      expense.ExpenseAddSingleFromMarkor4,
      expense.ExpenseAddSingleFromMarkor5,
      expense.ExpenseAddSingleFromMarkor6,
      expense.ExpenseAddSingleFromMarkor7,
      expense.ExpenseAddSingleFromMarkor8,
      expense.ExpenseAddSingleFromMarkor9,
      expense.ExpenseAddSingleFromMarkor10,
      expense.ExpenseAddSingleFromGallery,
      expense.ExpenseAddSingleFromGallery2,
      expense.ExpenseAddSingleFromGallery3,
      expense.ExpenseAddSingleFromGallery4,
      expense.ExpenseAddSingleFromGallery5,
      expense.ExpenseAddSingleFromGallery6,
      expense.ExpenseAddSingleFromGallery7,
      expense.ExpenseAddSingleFromGallery8,
      expense.ExpenseAddSingleFromGallery9,
      expense.ExpenseAddSingleFromGallery10,
      expense.ExpenseDeleteDuplicates,
      expense.ExpenseDeleteDuplicates2,
      expense.ExpenseDeleteDuplicates3,
      expense.ExpenseDeleteDuplicates4,
      expense.ExpenseDeleteDuplicates5,
      expense.ExpenseDeleteDuplicates6,
      expense.ExpenseDeleteDuplicates7,
      expense.ExpenseDeleteDuplicates8,
      expense.ExpenseDeleteDuplicates9,
      expense.ExpenseDeleteDuplicates10,
      expense.ExpenseDeleteMultiple,
      expense.ExpenseDeleteMultiple2,
      expense.ExpenseDeleteMultiple3,
      expense.ExpenseDeleteSingle,
      expense.ExpenseOpen,
      files.FilesDeleteFile,
      files.FilesMoveFile,
      files.FilesMoveFileAndDelete,
      files.FilesCreateFolder,
      markor.MarkorAddNoteHeader,
      markor.MarkorChangeNoteContent,
      markor.MarkorCreateFolder,
      markor.MarkorCreateNote,
      markor.MarkorCreateNoteFromClipboard,
      markor.MarkorDeleteAllNotes,
      markor.MarkorDeleteNewestNote,
      markor.MarkorDeleteNote,
      markor.MarkorEditNote,
      markor.MarkorMergeNotes,
      markor.MarkorMoveNote,
      markor.MarkorTranscribeReceipt,
      markor.MarkorTranscribeVideo,
      markor.MarkorOpen,
      markor.MarkorMoveNoteandCreateFolder,
      markor.MarkorCreateFolderthenCreateNote,
      markor.MarkorMoveAndEditNote,
      markor.MarkorMoveAndDeleteNote,
      markor.MarkorCreateFolderThenMoveNote,
      markor.MarkorCreateFolderThenCreateNoteFromClipboard,
      markorandcalender.MarkorCreateFolderandSimpleCalendarAddOneEvent,
      markorandcalender.MarkorCreateFolderwithCalender,
      # Markor composite tasks.
      markor_sms.MarkorCreateNoteAndSms,
      markor_sms.MarkorCreateNoteAndSmsRelpy,
      # OsmAnd.
      osmand.OsmAndFavorite,
      osmand.OsmAndFavorite2,
      osmand.OsmAndMarker,
      osmand.OsmAndMarker2,
      osmand.OsmAndTrack,
      osmand.OsmAndTrack2,
      recipe.BroccoliOpen,
      recipe.RecipeAddMultipleRecipes,
      recipe.RecipeAddMultipleRecipesFromImage,
      recipe.RecipeAddMultipleRecipesFromImage2,
      recipe.RecipeAddMultipleRecipesFromImage3,
      recipe.RecipeAddMultipleRecipesFromImage4,
      recipe.RecipeAddMultipleRecipesFromImage5,
      recipe.RecipeAddMultipleRecipesFromImage6,
      recipe.RecipeAddMultipleRecipesFromImage7,
      recipe.RecipeAddMultipleRecipesFromImage8,
      recipe.RecipeAddMultipleRecipesFromImage9,
      recipe.RecipeAddMultipleRecipesFromImage10,
      recipe.RecipeAddMultipleRecipesFromMarkor,
      recipe.RecipeAddMultipleRecipesFromMarkor2,
      recipe.RecipeAddMultipleRecipesFromMarkor3,
      recipe.RecipeAddMultipleRecipesFromMarkor4,
      recipe.RecipeAddMultipleRecipesFromMarkor5,
      recipe.RecipeAddMultipleRecipesFromMarkor6,
      recipe.RecipeAddMultipleRecipesFromMarkor7,
      recipe.RecipeAddMultipleRecipesFromMarkor8,
      recipe.RecipeAddMultipleRecipesFromMarkor9,
      recipe.RecipeAddMultipleRecipesFromMarkor10,
      recipe.RecipeAddSingleRecipe,
      recipe.RecipeDeleteDuplicateRecipes,
      recipe.RecipeDeleteDuplicateRecipes2,
      recipe.RecipeDeleteDuplicateRecipes3,
      recipe.RecipeDeleteMultipleRecipes,
      recipe.RecipeDeleteMultipleRecipes2,
      recipe.RecipeDeleteMultipleRecipesWithConstraint,
      recipe.RecipeDeleteMultipleRecipesWithNoise,
      recipe.RecipeDeleteMultipleRecipesWithNoise2,
      recipe.RecipeDeleteSingleRecipe,
      recipe.RecipeDeleteSingleWithRecipeWithNoise,
      retro_music.RetroCreatePlaylist,
      retro_music.RetroPlayingQueue,
      retro_music.RetroPlaylistDuration,
      retro_music.RetroSavePlaylist,
      retro_music.RetroOpen,
      simple_draw_pro.SimpleDrawProCreateDrawing,
      simple_draw_pro.SimpleDrawProOpen,
      simple_gallery_pro.SaveCopyOfReceiptTaskEval,
      sms.SmsOpen,
      sms.SimpleSmsReply,
      sms.SimpleSmsReplyMostRecent,
      sms.SimpleSmsResend,
      sms.SimpleSmsSend,
      sms.SimpleSmsSendClipboardContent,
      sms.SimpleSmsSendReceivedAddress,
      system.OpenAppTaskEval,
      system.SystemBluetoothTurnOff,
      system.SystemBluetoothTurnOffVerify,
      system.SystemBluetoothTurnOn,
      system.SystemBluetoothTurnOnVerify,
      system.SystemBrightnessMax,
      system.SystemBrightnessMaxVerify,
      system.SystemBrightnessMin,
      system.SystemBrightnessMinVerify,
      system.SystemCopyToClipboard,
      system.SystemWifiTurnOff,
      system.SystemWifiTurnOffVerify,
      system.SystemWifiTurnOn,
      system.SystemWifiTurnOnVerify,
      system_composite.TurnOffWifiAndTurnOnBluetooth,
      system_composite.TurnOnWifiAndOpenApp,
      system_composite.TurnOffWifiAndOpenApp,
      system_composite.TurnOnBlueToothAndOpenApp,
      system_composite.TurnOffBlueToothAndOpenApp,
      system_composite.BrightnessMaxAndOpenApp,
      system_composite.BrightnessMinAndOpenApp,
      system_composite.TurnOnWifiAndTurnOnBluetooth,
      system_composite.TurnOffWifiAndTurnOffBluetooth,
      system_composite.TurnOnWifiAndTurnOffBluetooth,
      system_composite.TurnOnWifiAndBrightnessMax,
      system_composite.TurnOnWifiAndBrightnessMin,
      system_composite.TurnOffWifiAndBrightnessMax,
      system_composite.TurnOffWifiAndBrightnessMin,
      system_composite.TurnOnBluetoothAndBrightnessMax,
      system_composite.TurnOnBluetoothAndBrightnessMin,
      system_composite.TurnOffBluetoothAndBrightnessMax,
      system_composite.TurnOffBluetoothAndBrightnessMin,
      system_composite.TurnOnWifiAndTurnOnBluetoothAndBrightnessMax,
      system_composite.TurnOnWifiAndTurnOnBluetoothAndBrightnessMin,
      system_composite.TurnOnWifiAndTurnOffBluetoothAndBrightnessMax,
      system_composite.TurnOnWifiAndTurnOffBluetoothAndBrightnessMin,
      system_composite.TurnOffWifiAndTurnOnBluetoothAndBrightnessMax,
      system_composite.TurnOffWifiAndTurnOnBluetoothAndBrightnessMin,
      system_composite.TurnOffWifiAndTurnOffBluetoothAndBrightnessMax,
      system_composite.TurnOffWifiAndTurnOffBluetoothAndBrightnessMin,
      system_composite.TurnOnWifiAndTurnOnBluetoothAndOpenApp,
      system_composite.TurnOffWifiAndTurnOffBluetoothAndOpenApp,
      system_composite.TurnOffWifiAndTurnOnBluetoothAndOpenApp,
      system_composite.TurnOnWifiAndTurnOffBluetoothAndOpenApp,
      system_composite.TurnOffBluetoothAndBrightnessMaxAndOpenApp,
      system_composite.TurnOffBluetoothAndBrightnessMinAndOpenApp,
      system_composite.TurnOnBluetoothAndBrightnessMaxAndOpenApp,
      system_composite.TurnOnBluetoothAndBrightnessMinAndOpenApp,
      system_composite.TurnOffWifiAndBrightnessMaxAndOpenApp,
      system_composite.TurnOnWifiAndBrightnessMaxAndOpenApp,
      system_composite.TurnOffWifiAndBrightnessMinAndOpenApp,
      system_composite.TurnOnWifiAndBrightnessMinAndOpenApp,
      # keep-sorted end
      # VLC media player tasks.
      vlc.VlcCreatePlaylist,
      vlc.VlcCreateTwoPlaylists,
      vlc.VlcCreateThreePlaylists,
      # composite tasks.
      audio_recorder_camera.AudioRecorderOpenAndCameraOpen,
      audio_recorder_camera.AudioRecorderRecordAudioAndCameraOpen,
      audio_recorder_camera.AudioRecorderRecordAudioWithSettingsAndCameraOpen,
      audio_recorder_camera.AudioRecorderRecordAudioWithFileNameAndCameraOpen,
      audio_recorder_camera.AudioOpenAndCameraTakePhoto,
      audio_recorder_camera.AudioOpenAndCameraTakeVideo,
      audio_recorder_camera.AudioOpenAndCameraTakePhotos,
      audio_recorder_camera.AudioOpenAndCameraTakeVideos,
      audio_recorder_camera.AudioRecorderRecordAudioAndCameraTakePhoto,
      audio_recorder_camera.AudioRecorderRecordAudioAndCameraTakePhotos,
      audio_recorder_camera.AudioRecorderRecordAudioAndCameraTakeVideo,
      audio_recorder_camera.AudioRecorderRecordAudioAndCameraTakeVideos,
      audio_recorder_camera.AudioRecorderRecordAudioWithFileNameAndCameraTakePhoto,
      audio_recorder_camera.AudioRecorderRecordAudioWithFileNameAndCameraTakePhotos,
      audio_recorder_camera.AudioRecorderRecordAudioWithFileNameAndCameraTakeVideos,
      audio_recorder_camera.AudioRecorderRecordAudioWithFileNameAndCameraTakeVideo,
      audio_recorder_camera.AudioRecorderRecordAudioWithSettingsAndCameraTakePhoto,
      audio_recorder_camera.AudioRecorderRecordAudioWithSettingsAndCameraTakeVideo,
      audio_recorder_camera.AudioRecorderRecordAudioWithSettingsAndCameraTakeVideos,
      audio_recorder_camera.AudioRecorderRecordAudioWithFileNameAndCameraTakePhotoAndVideo,
      audio_recorder_clock.AudioRecoderOpenAndClockOpen,
      audio_recorder_clock.AudioRecorderRecordAudioAndClockOpen,
      audio_recorder_clock.AudioRecorderRecordAudioWithSettingsAndClockOpen,
      audio_recorder_clock.AudioRecorderRecordAudioWithFileNameAndClockOpen,
      audio_recorder_clock.AudioRecorderRecordAudioAndClockStopWatchPaused,
      audio_recorder_clock.AudioRecorderRecordAudioAndStopWatchRunning,
      audio_recorder_clock.AudioRecorderRecordAudioAndStopWatchRunningAndReset,
      audio_recorder_clock.AudioRecorderRecordAudioWithSettingsAndClockTimerEntry,
      audio_recorder_clock.AudioRecorderRecordAudioWithSettingsAndClockStopWatchPaused,
      audio_recorder_clock.AudioRecorderRecordAudioAndClockTimerEntry,
      audio_recorder_clock.AudioRecorderRecordAudioAndClockStopWatchRunningAndPaused,
      audio_recorder_clock.AudioRecorderRecordAudioWithSettingsAndClockStopWatchRunning,
      audio_recorder_clock.AudioRecorderRecordAudioWithSettingsAndClockStopWatchRunningAndPaused,
      audio_recorder_clock.AudioRecorderRecordAudioWithSettingsAndClockWatchRunningAndReset,
      audio_recorder_clock.AudioRecorderRecordAudioWithFileNameAndClockStopWatchPaused,
      audio_recorder_clock.AudioRecorderRecordAudioWithFileNameAndClockStopWatchRunning,
      audio_recorder_clock.AudioRecorderRecordAudioWithFileNameAndClockWatchRunningAndReset,
      audio_recorder_clock.AudioRecorderRecordAudioWithFileNameAndClockStopWatchRunningAndPaused,
      recipe_gallery.RecipeAddMultipleRecipesAndGallery,
      recipe_gallery.RecipeAddMultipleRecipesFromImage,
      recipe_gallery.RecipeAddMultipleRecipesFromImageAndGallery2,
      recipe_gallery.RecipeAddMultipleRecipesFromImageAndGallery3,
      recipe_gallery.RecipeAddMultipleRecipesFromImageAndGallery4,
      recipe_gallery.RecipeAddMultipleRecipesFromImageAndGallery5,
      recipe_gallery.RecipeAddMultipleRecipesFromMarkor,
      recipe_gallery.RecipeAddMultipleRecipesFromMarkorAndGallery2,
      recipe_gallery.RecipeAddMultipleRecipesFromMarkorAndGallery3,
      recipe_gallery.RecipeAddMultipleRecipesFromMarkorAndGallery4,
      recipe_gallery.RecipeAddMultipleRecipesFromMarkorAndGallery5,
      recipe_gallery.RecipeAddSingleRecipe,
      recipe_gallery.RecipeDeleteDuplicateRecipes,
      recipe_gallery.RecipeDeleteDuplicateRecipes2,
      recipe_gallery.RecipeDeleteDuplicateRecipes3,
      recipe_gallery.RecipeDeleteMultipleRecipesAndGallery,
      recipe_gallery.RecipeDeleteMultipleRecipes2AndGallery,
      recipe_gallery.RecipeDeleteMultipleRecipesWithConstraintAndGallery,
      recipe_gallery.RecipeDeleteMultipleRecipesWithNoiseAndGallery,
      recipe_gallery.RecipeDeleteMultipleRecipesWithNoise2AndGallery,
      recipe_gallery.RecipeDeleteSingleRecipeAndGallery,
      recipe_gallery.RecipeDeleteSingleWithRecipeWithNoiseAndGallery,
      camera_clock.CameraOpenAndClockOpen,
      camera_clock.CameraTakeVideoAndClockStopWatchPaused,
      camera_clock.CameraTakeVideoAndClockStopWatchRunning,
      camera_clock.CameraTakeVideoAndClockWatchRunningAndReset,
      camera_clock.CameraTakeVideosAndClockStopWatchRunning,
      camera_clock.CameraTakeVideosAndClockWatchRunningAndReset,
      camera_clock.CameraTakeVideosAndClockStopWatchPaused,
      camera_clock.CameraTakeVideoAndClockStopWatchRunningAndPaused,
      camera_clock.CameraTakeVideosAndClockStopWatchRunningAndPaused,
      camera_clock.CameraTakePhotosAndClockWatchRunningAndReset,
      camera_clock.CameraTakePhotoAndClockStopWatchRunning,
      camera_clock.CameraTakePhotosAndClockStopWatchRunning,
      camera_clock.CameraTakePhotoAndClockStopWatchPaused,
      camera_clock.CameraTakePhotoAndClockStopWatchRunningAndPaused,
      camera_clock.CameraTakePhotoAndClockWatchRunningAndReset,
      camera_clock.CameraTakePhotosAndClockStopWatchPaused,
      camera_clock.CameraTakePhotosAndClockStopWatchRunningAndPaused,
      camera_clock.CameraTakePhotosAndVideosAndClockStopWatchRunningAndPaused,
      camera_clock.CameraTakePhotosAndVideosAndClockWatchRunningAndReset,
      camera_clock.CameraTakePhotoAndVideoAndClockStopWatchPaused,
      camera_clock.CameraTakePhotoAndVideoAndClockStopWatchRunning,
      camera_clock.CameraTakePhotoAndVideoAndClockStopWatchRunningAndPaused,
      camera_clock.CameraTakePhotoAndAndClockWatchRunningAndReset,
      camera_clock.CameraTakePhotosAndVideosAndClockStopWatchPaused,
      camera_clock.CameraTakePhotosAndVideosAndClockStopWatchRunning,
      camera_clock.CameraTakeVideoAndClockOpen,
      camera_clock.CameraTakeVideosAndClockOpen,
      camera_clock.CameraTakePhotoAndClockOpen,
      camera_clock.CameraTakePhotosAndClockOpen,
      camera_clock.CameraTakePhotoAndVideoAndClockOpen,
      camera_clock.CameraTakePhotosAndVideosAndClockOpen,
      camera_clock.CameraOpenAndClockWatchRunningAndReset,
      camera_clock.CameraOpenAndClockStopWatchPaused,
      camera_clock.CameraOpenAndClockStopWatchRunning,
      camera_clock.CameraOpenAndClockStopWatchRunningAndPaused,
      camera_clock.CameraTakeVideosAndPhotosAndClockEntry,
      camera_clock.CameraTakeVideoAndPhotoAndClockEntry,
      camera_clock.CameraTakeVideoAndClockEntry,
      camera_clock.CameraTakeVideosAndClockEntry,
      camera_clock.CameraTakePhotoAndClockEntry,
      camera_clock.CameraTakePhotosAndClockEntry,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndTakeVideo,
      system_camera.TurnOffBluetoothAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOffBluetoothAndBrightnessMinAndTakeVideo,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndTakeVideo,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndTakeVideo,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndTakeVideo,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndTakeVideo,
      system_camera.TurnOffWifiAndBrightnessMinAndTakeVideo,
      system_camera.TurnOnWifiAndBrightnessMinAndTakeVideo,
      system_camera.TurnOffWifiAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOnWifiAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOnBluetoothAndBrightnessMinAndTakeVideo,
      system_camera.TurnOnBluetoothAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndTakeVideo,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndTakeVideo,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndTakeVideo,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndTakeVideo,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndTakeVideos,
      system_camera.TurnOffBluetoothAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOffBluetoothAndBrightnessMinAndTakeVideos,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndTakeVideos,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndTakeVideos,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndTakeVideos,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndTakeVideos,
      system_camera.TurnOffWifiAndBrightnessMinAndTakeVideos,
      system_camera.TurnOnWifiAndBrightnessMinAndTakeVideos,
      system_camera.TurnOffWifiAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOnWifiAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOnBluetoothAndBrightnessMinAndTakeVideos,
      system_camera.TurnOnBluetoothAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndTakeVideos,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndTakeVideos,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndTakeVideos,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndTakeVideos,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndTakePhoto,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndTakePhoto,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndTakePhoto,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndTakePhoto,
      system_camera.TurnOffWifiAndBrightnessMinAndTakePhoto,
      system_camera.TurnOnWifiAndBrightnessMinAndTakePhoto,
      system_camera.TurnOffWifiAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOnWifiAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOnBluetoothAndBrightnessMinAndTakePhoto,
      system_camera.TurnOnBluetoothAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOffBluetoothAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOffBluetoothAndBrightnessMinAndTakePhoto,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndTakePhoto,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndTakePhoto,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndTakePhoto,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndTakePhoto,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndTakePhoto,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndTakePhotos,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndTakePhotos,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndTakePhotos,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndTakePhotos,
      system_camera.TurnOffWifiAndBrightnessMinAndTakePhotos,
      system_camera.TurnOnWifiAndBrightnessMinAndTakePhotos,
      system_camera.TurnOffWifiAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOnWifiAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOnBluetoothAndBrightnessMinAndTakePhotos,
      system_camera.TurnOnBluetoothAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOffBluetoothAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOffBluetoothAndBrightnessMinAndTakePhotos,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndTakePhotos,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndTakePhotos,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndTakePhotos,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndTakePhotos,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndTakePhotos,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndTakePhotoAndVideo,
      system_camera.TurnOffBluetoothAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOffBluetoothAndBrightnessMinAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndTakePhotoAndVideo,
      system_camera.TurnOnWifiAndTurnOnBluetoothAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndTakePhotoAndVideo,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndBrightnessMinAndTakePhotoAndVideo,
      system_camera.TurnOnWifiAndBrightnessMinAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOnWifiAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOnBluetoothAndBrightnessMinAndTakePhotoAndVideo,
      system_camera.TurnOnBluetoothAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndTakePhotoAndVideo,
      system_camera.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndTakePhotoAndVideo,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndClockTimerEntry,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndClockTimerEntry,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndClockTimerEntry,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndClockTimerEntry,
      system_clock.TurnOffWifiAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOnWifiAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOffWifiAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOnWifiAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOnBluetoothAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOnBluetoothAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOffBluetoothAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOffBluetoothAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndClockTimerEntry,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndClockTimerEntry,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOnBluetoothAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOnBluetoothAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOffBluetoothAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOffBluetoothAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchPausedVerify,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOnBluetoothAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOffBluetoothAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchRunning,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnBluetoothAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffBluetoothAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchRunningAndPaused,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndClockStopWatchRunningAndReset,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndClockStopWatchRunningAndReset,
      system_clock.TurnOffWifiAndBrightnessMinAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndBrightnessMinAndClockStopWatchRunningAndReset,
      system_clock.TurnOffWifiAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOnBluetoothAndBrightnessMinAndClockStopWatchRunningAndReset,
      system_clock.TurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOffBluetoothAndBrightnessMinAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOnWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchRunningAndReset,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOffWifiAndTurnOnBluetoothAndBrightnessMinAndClockStopWatchRunningAndReset,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMaxAndClockStopWatchRunningAndReset,
      system_clock.TurnOffWifiAndTurnOffBluetoothAndBrightnessMinAndClockStopWatchRunningAndReset,
      calendar_clock.SimpleCalendarAddOneEventAndStopWatchPaused,
      calendar_clock.SimpleCalendarAddOneEventAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarAddOneEventAndClockStopWatchRunningAndPaused,
      calendar_clock.SimpleCalendarAddOneEventAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarAddOneEventTomorrowAndStopWatchPaused,
      calendar_clock.SimpleCalendarAddOneEventTomorrowAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarAddOneEventTomorrowAndClockStopWatchRunningAndPaused,
      calendar_clock.SimpleCalendarAddOneEventTomorrowAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarAddOneEventInOneWeekAndStopWatchPaused,
      calendar_clock.SimpleCalendarAddOneEventInOneWeekAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarAddOneEventInOneWeekAndClockStopWatchRunningAndPaused,
      calendar_clock.SimpleCalendarAddOneEventInOneWeekAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarAddOneEventInTwoWeeksAndStopWatchPaused,
      calendar_clock.SimpleCalendarAddOneEventInTwoWeeksAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarAddOneEventInTwoWeeksAndClockStopWatchRunningAndPaused,
      calendar_clock.SimpleCalendarAddOneEventInTwoWeeksAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarAddOneEventInOneMonthAndStopWatchPaused,
      calendar_clock.SimpleCalendarAddOneEventInOneMonthAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarAddOneEventInOneMonthAndClockStopWatchRunningAndPaused,
      calendar_clock.SimpleCalendarAddOneEventInOneMonthAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarAddOneEventInTwoMonthAndStopWatchPaused,
      calendar_clock.SimpleCalendarAddOneEventInTwoMonthAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarAddOneEventInTwoMonthAndClockStopWatchRunningAndPaused,
      calendar_clock.SimpleCalendarAddOneEventInTwoMonthAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarAddRepeatingEventAndStopWatchPaused,
      calendar_clock.SimpleCalendarAddRepeatingEventAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarAddRepeatingEventAndClockStopWatchRunningAndPaused,
      calendar_clock.SimpleCalendarAddRepeatingEventAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarDeleteEventsAndStopWatchPaused,
      calendar_clock.SimpleCalendarDeleteEventsAndClockStopWatchRunning,
      calendar_clock.SimpleCalendarDeleteEventsAndClockWatchRunningAndReset,
      calendar_clock.SimpleCalendarDeleteEventsAndClockStopWatchRunningAndPaused,
      Markor_single_draw_pro.MarkorMoveNoteandCreateFolderAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorCreateFolderthenCreateNoteAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorMoveNoteAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorCreateFolderAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorCreateNoteAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorCreateNoteFromClipboardAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorMergeNotesAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorChangeNoteContentAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorAddNoteHeaderAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorEditNoteAndSimpleDrawProCreateDrawing,
      Markor_single_draw_pro.MarkorMoveNoteandCreateFolderAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorCreateFolderthenCreateNoteAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorMoveNoteAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorCreateFolderAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorCreateNoteAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorCreateNoteFromClipboardAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorMergeNotesAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorChangeNoteContentAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorAddNoteHeaderAndSimpleDrawProCreateDrawing2,
      Markor_single_draw_pro.MarkorEditNoteAndSimpleDrawProCreateDrawing2,
      Markor_Camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideo,
      Markor_Camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideo,
      Markor_Camera.MarkorMoveNoteAndCameraTakeVideo,
      Markor_Camera.MarkorCreateFolderAndCameraTakeVideo,
      Markor_Camera.MarkorCreateNoteAndCameraTakeVideo,
      Markor_Camera.MarkorCreateNoteFromClipboardAndCameraTakeVideo,
      Markor_Camera.MarkorMergeNotesAndCameraTakeVideo,
      Markor_Camera.MarkorChangeNoteContentAndCameraTakeVideo,
      Markor_Camera.MarkorAddNoteHeaderAndCameraTakeVideo,
      Markor_Camera.MarkorEditNoteAndCameraTakeVideo,
      Markor_Camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideos,
      Markor_Camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideos,
      Markor_Camera.MarkorMoveNoteAndCameraTakeVideos,
      Markor_Camera.MarkorCreateFolderAndCameraTakeVideos,
      Markor_Camera.MarkorCreateNoteAndCameraTakeVideos,
      Markor_Camera.MarkorCreateNoteFromClipboardAndCameraTakeVideos,
      Markor_Camera.MarkorMergeNotesAndCameraTakeVideos,
      Markor_Camera.MarkorChangeNoteContentAndCameraTakeVideos,
      Markor_Camera.MarkorAddNoteHeaderAndCameraTakeVideos,
      Markor_Camera.MarkorEditNoteAndCameraTakeVideos,
      Markor_Camera.MarkorMoveNoteandCreateFolderAndCameraTakePhoto,
      Markor_Camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhoto,
      Markor_Camera.MarkorMoveNoteAndCameraTakePhoto,
      Markor_Camera.MarkorCreateFolderAndCameraTakePhoto,
      Markor_Camera.MarkorCreateNoteAndCameraTakePhoto,
      Markor_Camera.MarkorCreateNoteFromClipboardAndCameraTakePhoto,
      Markor_Camera.MarkorMergeNotesAndCameraTakePhoto,
      Markor_Camera.MarkorChangeNoteContentAndCameraTakePhoto,
      Markor_Camera.MarkorAddNoteHeaderAndCameraTakePhoto,
      Markor_Camera.MarkorEditNoteAndCameraTakePhoto,
      Markor_Camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotos,
      Markor_Camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotos,
      Markor_Camera.MarkorMoveNoteAndCameraTakePhotos,
      Markor_Camera.MarkorCreateFolderAndCameraTakePhotos,
      Markor_Camera.MarkorCreateNoteAndCameraTakePhotos,
      Markor_Camera.MarkorCreateNoteFromClipboardAndCameraTakePhotos,
      Markor_Camera.MarkorMergeNotesAndCameraTakePhotos,
      Markor_Camera.MarkorChangeNoteContentAndCameraTakePhotos,
      Markor_Camera.MarkorAddNoteHeaderAndCameraTakePhotos,
      Markor_Camera.MarkorEditNoteAndCameraTakePhotos,
      Markor_Camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorMoveNoteAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorCreateFolderAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorCreateNoteAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorCreateNoteFromClipboardAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorMergeNotesAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorChangeNoteContentAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorAddNoteHeaderAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorEditNoteAndCameraTakePhotoAndVideo,
      Markor_Camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorMoveNoteAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorCreateFolderAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorCreateNoteAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorCreateNoteFromClipboardAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorMergeNotesAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorChangeNoteContentAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorAddNoteHeaderAndCameraTakePhotosAndVideos,
      Markor_Camera.MarkorEditNoteAndCameraTakePhotosAndVideos,
      markor_audio_recorder.MarkorMoveNoteandCreateFolderAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorCreateFolderthenCreateNoteAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorMoveNoteAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorCreateFolderAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorCreateNoteAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorCreateNoteFromClipboardAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorMergeNotesAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorChangeNoteContentAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorAddNoteHeaderAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorEditNoteAndAudioRecorderRecordAudio,
      markor_audio_recorder.MarkorMoveNoteandCreateFolderAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorCreateFolderthenCreateNoteAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorMoveNoteAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorCreateFolderAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorCreateNoteAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorCreateNoteFromClipboardAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorMergeNotesAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorChangeNoteContentAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorAddNoteHeaderAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorEditNoteAndAudioRecorderRecordAudioWithSettings,
      markor_audio_recorder.MarkorMoveNoteandCreateFolderAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorCreateFolderthenCreateNoteAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorMoveNoteAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorCreateFolderAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorCreateNoteAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorCreateNoteFromClipboardAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorMergeNotesAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorChangeNoteContentAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorAddNoteHeaderAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorEditNoteAndAudioRecorderRecordAudioWithFileName,
      markor_audio_recorder.MarkorMoveNoteandCreateFolderAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorCreateFolderthenCreateNoteAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorMoveNoteAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorCreateFolderAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorCreateNoteAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorCreateNoteFromClipboardAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorMergeNotesAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorChangeNoteContentAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorAddNoteHeaderAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_audio_recorder.MarkorEditNoteAndAudioRecorderRecordAudioWithSettingsAndFileName,
      markor_clock.MarkorMoveNoteandCreateFolderAndClockStopWatchPausedVerify,
      markor_clock.MarkorCreateFolderthenCreateNoteAndClockStopWatchPausedVerify,
      markor_clock.MarkorMoveNoteAndClockStopWatchPausedVerify,
      markor_clock.MarkorCreateFolderAndClockStopWatchPausedVerify,
      markor_clock.MarkorCreateNoteAndClockStopWatchPausedVerify,
      markor_clock.MarkorCreateNoteFromClipboardAndClockStopWatchPausedVerify,
      markor_clock.MarkorMergeNotesAndClockStopWatchPausedVerify,
      markor_clock.MarkorChangeNoteContentAndClockStopWatchPausedVerify,
      markor_clock.MarkorAddNoteHeaderAndClockStopWatchPausedVerify,
      markor_clock.MarkorEditNoteAndClockStopWatchPausedVerify,
      markor_clock.MarkorMoveNoteandCreateFolderAndClockStopWatchRunning,
      markor_clock.MarkorCreateFolderthenCreateNoteAndClockStopWatchRunning,
      markor_clock.MarkorMoveNoteAndClockStopWatchRunning,
      markor_clock.MarkorCreateFolderAndClockStopWatchRunning,
      markor_clock.MarkorCreateNoteAndClockStopWatchRunning,
      markor_clock.MarkorCreateNoteFromClipboardAndClockStopWatchRunning,
      markor_clock.MarkorMergeNotesAndClockStopWatchRunning,
      markor_clock.MarkorChangeNoteContentAndClockStopWatchRunning,
      markor_clock.MarkorAddNoteHeaderAndClockStopWatchRunning,
      markor_clock.MarkorEditNoteAndClockStopWatchRunning,
      markor_clock.MarkorMoveNoteandCreateFolderAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorCreateFolderthenCreateNoteAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorMoveNoteAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorCreateFolderAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorCreateNoteAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorCreateNoteFromClipboardAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorMergeNotesAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorChangeNoteContentAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorAddNoteHeaderAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorEditNoteAndClockStopWatchRunningAndPaused,
      markor_clock.MarkorMoveNoteandCreateFolderAndClockWatchRunningAndReset,
      markor_clock.MarkorCreateFolderthenCreateNoteAndClockWatchRunningAndReset,
      markor_clock.MarkorMoveNoteAndClockWatchRunningAndReset,
      markor_clock.MarkorCreateFolderAndClockWatchRunningAndReset,
      markor_clock.MarkorCreateNoteAndClockWatchRunningAndReset,
      markor_clock.MarkorCreateNoteFromClipboardAndClockWatchRunningAndReset,
      markor_clock.MarkorMergeNotesAndClockWatchRunningAndReset,
      markor_clock.MarkorChangeNoteContentAndClockWatchRunningAndReset,
      markor_clock.MarkorAddNoteHeaderAndClockWatchRunningAndReset,
      markor_clock.MarkorEditNoteAndClockWatchRunningAndReset,
      markor_clock.MarkorMoveNoteandCreateFolderAndClockTimerEntry,
      markor_clock.MarkorCreateFolderthenCreateNoteAndClockTimerEntry,
      markor_clock.MarkorMoveNoteAndClockTimerEntry,
      markor_clock.MarkorCreateFolderAndClockTimerEntry,
      markor_clock.MarkorCreateNoteAndClockTimerEntry,
      markor_clock.MarkorCreateNoteFromClipboardAndClockTimerEntry,
      markor_clock.MarkorMergeNotesAndClockTimerEntry,
      markor_clock.MarkorChangeNoteContentAndClockTimerEntry,
      markor_clock.MarkorAddNoteHeaderAndClockTimerEntry,
      markor_clock.MarkorEditNoteAndClockTimerEntry,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorMoveNoteAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorCreateFolderAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorCreateNoteAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorMergeNotesAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorEditNoteAndCameraTakeVideoAndStopWatch,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorMoveNoteAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorCreateFolderAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorCreateNoteAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorMergeNotesAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorEditNoteAndCameraTakeVideosAndStopWatch,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorMoveNoteAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorCreateFolderAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorCreateNoteAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorMergeNotesAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorEditNoteAndCameraTakePhotoAndStopWatch,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorMoveNoteAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorCreateFolderAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorCreateNoteAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorMergeNotesAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorEditNoteAndCameraTakePhotosAndStopWatch,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorMergeNotesAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorEditNoteAndCameraTakeVideoAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorMergeNotesAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorEditNoteAndCameraTakeVideosAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorMergeNotesAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorEditNoteAndCameraTakePhotoAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateFolderAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorMergeNotesAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorEditNoteAndCameraTakePhotosAndStopWatchRunning,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMoveNoteAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMergeNotesAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorEditNoteAndCameraTakeVideoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMoveNoteAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMergeNotesAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorEditNoteAndCameraTakeVideosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMoveNoteAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMergeNotesAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorEditNoteAndCameraTakePhotoAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMoveNoteandCreateFolderAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderthenCreateNoteAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMoveNoteAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateFolderAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorCreateNoteFromClipboardAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorMergeNotesAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorChangeNoteContentAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorAddNoteHeaderAndCameraTakePhotosAndStopWatchRunningAndPause,
      markor_clock_camera.MarkorEditNoteAndCameraTakePhotosAndStopWatchRunningAndPause,
      Markor_camera_audio.MarkorMoveNoteandCreateFolderAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderthenCreateNoteAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorMoveNoteAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteFromClipboardAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorMergeNotesAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorChangeNoteContentAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorAddNoteHeaderAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorEditNoteAndCameraTakeVideoAndAudiorecorder,
      Markor_camera_audio.MarkorMoveNoteandCreateFolderAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderthenCreateNoteAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorMoveNoteAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteFromClipboardAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorMergeNotesAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorChangeNoteContentAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorAddNoteHeaderAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorEditNoteAndCameraTakeVideosAndAudiorecorder,
      Markor_camera_audio.MarkorMoveNoteandCreateFolderAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderthenCreateNoteAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorMoveNoteAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteFromClipboardAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorMergeNotesAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorChangeNoteContentAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorAddNoteHeaderAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorEditNoteAndCameraTakePhotoAndAudiorecorder,
      Markor_camera_audio.MarkorMoveNoteandCreateFolderAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderthenCreateNoteAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorMoveNoteAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateFolderAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorCreateNoteFromClipboardAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorMergeNotesAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorChangeNoteContentAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorAddNoteHeaderAndCameraTakePhotosAndAudiorecorder,
      Markor_camera_audio.MarkorEditNoteAndCameraTakePhotosAndAudiorecorder,
      phone.MarkorCallApartment,
      phone.PhoneAnswerCall,
      phone.PhoneCallTextSender,
      phone.PhoneMakeCall,
      phone.PhoneRedialNumber,
      phone.PhoneReturnMissedCall,
      sms.SimpleSmsSendAfterCall,



  )

  def register_task(
      self, task_registry: dict[Any, Any], task_class: type[task_eval.TaskEval]
  ) -> None:
    """Registers the task class.

    Args:
      task_registry: The registry to register the task in.
      task_class: The class to register.
    """
    task_registry[task_class.__name__] = task_class

  def __init__(self):
    for task in self._TASKS:
      self.register_task(self.ANDROID_TASK_REGISTRY, task)

  # Add names with "." notation for autocomplete in Colab.
  names = types.SimpleNamespace(**{
      k: k
      for k in {
          **ANDROID_TASK_REGISTRY,
          **INFORMATION_RETRIEVAL_TASK_REGISTRY,
          **MINIWOB_TASK_REGISTRY,
          **MINIWOB_TASK_REGISTRY,
      }
  })
